### ISSUE TITLE
Add updateShipmentLine method to ExtDirectExpedition.class.php

### ISSUE THREAD

**Issue by fappels** [fappels/dolibarrextdirect#4]
Add update/delete shipment line possibility, to be transferred later to Dolibarr 6.0

**Comment by fappels** [comment]
transfered to Dolibarr 7.0

**Comment by BebZ** [comment]
Hey Francis,

does it mean in version 7.0 we can correct shipment lines after or before
"validate shipment" ?

Thanks


*Hubert ANDRIOLO*
*Gérant F.M. MEDICAL et NORD HYGIENE*
Mobile: +33 (0) 6 23 10 17 31
Fax: +33 (0) 9 56 51 95 71
Site: www.fournisseur-medical.com


*FM MEDICAL - NORD HYGIENE*
*2 RUE DE LA JUSTICE *
*62410 BENIFONTAINE *
SIRET : 532 788 700 00021
N° de TVA : FR15 532 788 700

2017-11-27 21:24 GMT+01:00 Francis Appels <notifications@github.com>:
